import Head from "next/head";
import Image from "next/image";
import Login from "../components/auth/Login";
import Dashboard from "../components/dashboard/Dashboard";
import SalesPoint from "../components/salespoint/SalesPoint";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" h-[100vh] ">{<Login />}</main>
    </div>
  );
}
